- name: Install tools, clone repos and start services
  hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
    - name: Install required apt packages
      ansible.builtin.apt:
        name:
          - nginx
          - git
          - gobuster
        state: present
        update_cache: yes

    - name: Ensure /opt exists
      ansible.builtin.file:
        path: /opt
        state: directory
        mode: '0755'

    - name: Clone SecLists from GitHub
      ansible.builtin.git:
        repo: 'https://github.com/danielmiessler/SecLists.git'
        dest: /opt/SecLists
        version: HEAD
        update: yes
        force: no

    - name: Clone BloodHound from GitHub
      ansible.builtin.git:
        repo: 'https://github.com/SpecterOps/BloodHound-Legacy/releases/download/v4.3.1/BloodHound-linux-x64.zip'
        dest: /opt/Bloodhound
        version: HEAD
        update: yes
        force: no

    - name: Start and enable nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
